spring:
  application:
    name: promptcanvas

  datasource:
    url: jdbc:postgresql://localhost:9000/promptcanvasDB
    username: testUser
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temperature: 0.0
jwt:
  secret-key: promptcanvas-dev-jwt-secret-key-not-for-production-use-2026

stripe:
  api:
    secret: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET_KEY}

client:
  url: http://localhost:8080 # Change it to your frontend url (using for success/failure of payment through stripe)

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
